routes/web.php
<?php

use App\Models\Kriteria;
use App\Models\Alternatif;
use App\Models\SubKriteria;
use App\Http\Controllers\DataPetugas;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\AlternatifController;
use App\Http\Controllers\PerhitunganController;
use App\Http\Controllers\SubkriteriaController;
use App\Http\Controllers\AlternatifDetailController;
use App\Http\Controllers\PerhitunganSubkriteriaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/logout', [LoginController::class, 'logout']);

Route::group(['middleware' => 'auth'], function () {
    // Halaman Dashboard
    Route::get('/dashboard', function () {
        return view('pages.index', [
            "title" => 'Dashboard',
            "active" => "dashboard",
            "alternatif" => Alternatif::get()->count(),
            "kriteria" => Kriteria::get()->count(),
            "subkriteria" => SubKriteria::get()->count(),
        ]);
    });

    Route::resource('kriteria', KriteriaController::class);
    Route::resource('subkriteria', SubkriteriaController::class);

    Route::get('/alternatif', [AlternatifController::class, 'index']);
    Route::post('/alternatif/store', [AlternatifController::class, 'store']);
    Route::get('/alternatif/edit', [AlternatifController::class, 'edit']);
    Route::put('/alternatif/update', [AlternatifController::class, 'update']);
    Route::delete('/alternatif/destroy', [AlternatifController::class, 'destroy']);

    Route::get('/alternatif_detail', [AlternatifDetailController::class, 'index']);
    Route::post('/alternatif_detail/store', [AlternatifDetailController::class, 'store']);
    Route::get('/alternatif_detail/edit', [AlternatifDetailController::class, 'edit']);
    Route::put('/alternatif_detail/update', [AlternatifDetailController::class, 'update']);
    Route::delete('/alternatif_detail/destroy', [AlternatifDetailController::class, 'destroy']);

    Route::get('/perhitungan', [PerhitunganController::class, 'index']);
    Route::post('/perhitungan/store', [PerhitunganController::class, 'store']);
    Route::get('/perhitungan/hasil', [PerhitunganController::class, 'hasil']);
    Route::get('/perhitungan/edit', [PerhitunganController::class, 'edit']);
    Route::put('/perhitungan/update', [PerhitunganController::class, 'update']);
    Route::delete('/perhitungan/destroy', [PerhitunganController::class, 'destroy']);

    Route::get('/perhitungan_subkriteria', [PerhitunganSubkriteriaController::class, 'index']);
    Route::get('/perhitungan_subkriteria/matrix', [PerhitunganSubkriteriaController::class, 'matrix']);
    Route::get('/perhitungan_subkriteria/hasil', [PerhitunganSubkriteriaController::class, 'hasil']);
    Route::get('/perhitungan_subkriteria/alternatif', [PerhitunganSubkriteriaController::class, 'alternatif']);
    Route::get('/perhitungan_subkriteria/prangkingan', [PerhitunganSubkriteriaController::class, 'prangkingan']);
    Route::post('/perhitungan_subkriteria/store', [PerhitunganSubkriteriaController::class, 'store']);
    Route::get('/perhitungan_subkriteria/edit', [PerhitunganSubkriteriaController::class, 'edit']);
    Route::put('/perhitungan_subkriteria/update', [PerhitunganSubkriteriaController::class, 'update']);
    Route::delete('/perhitungan_subkriteria/destroy', [PerhitunganSubkriteriaController::class, 'destroy']);

    Route::resource('/datapengguna', DataPetugas::class)->except('show', 'create');
});

app/Models/SubKriteria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class SubKriteria extends Model
{
    use HasFactory;

    public function kriteria() : HasOne {
        return $this->hasOne(Kriteria::class, 'id', 'id_kriteria');
    }

    public function perhitungansubkriterias(): HasMany {
        return $this->hasMany(PerhitunganSubkriteria::class, 'id_subkriteria', 'id');
    }
}

app/Http/Controllers/SubKriteriaController.php
<?php

namespace App\Http\Controllers;

use App\Models\SubKriteria;
use App\Models\Kriteria;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SubKriteriaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $id = $request->query('id');
        if ($id == null) {
            return redirect('kriteria');
        }

        $kriteria = Kriteria::findOrFail($id);
        $subkriterias = Subkriteria::where('id_kriteria', $id)->paginate(10);

        return view('pages.subkriteria.index', compact('subkriterias', 'kriteria'));
    }


    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $subkriteriaModel = new SubKriteria();
        $subkriteriaModel->nama_subkriteria = $request->nama_subkriteria;
        $subkriteriaModel->id_kriteria = $request->id_kriteria;

        $subkriteriaModel->save();
        return redirect('/subkriteria?id=' . $request->id_kriteria)->with('success', 'Berhasil menambahkan subkriteria');
    }

    /**
     * Display the specified resource.
     */
    public function show(SubKriteria $subKriteria)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(SubKriteria $subKriteria)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, SubKriteria $subKriteria)
    {
        $id = $request->input('id_subkriteria');
        $subkriteria = Subkriteria::where('id', $id)->first();
        $subkriteria->nama_subkriteria = $request->input('nama_subkriteria');
        $id_kriteria = $subkriteria->id_kriteria;
        $subkriteria->save();
        return redirect('/subkriteria?id=' . $id_kriteria)->with('success', 'Berhasil edit subkriteria');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Request $request)
    {
        $id = $request->input('id_subkriteria');
        $subkriteria = Subkriteria::where('id', $id)->first();
        $id_kriteria = $subkriteria->id_kriteria;
        $subkriteria->delete();
        return redirect('/subkriteria?id=' . $id_kriteria)->with('success', 'Berhasil menghapus subkriteria');
    }
}

resources/views/pages/subkriteria/index.blade.php
<x-app-layout>

    @slot('content')

    <div class="container-fluid px-4">
        @section('title')List Subkriteria @endsection
        <h4 class="mb-2 mt-4 text-capitalize">List Subkriteria {{ $kriteria->nama_kriteria }}</h4>
        <hr>

        <div class="card col-12 p-4 mb-5">
            <div class="col-12">
                <a href="/kriteria" class="btn btn-warning">
                    Kembali
                </a>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    Tambah Subkriteria
                </button>
            </div>
            <table class="table table-striped border">
                <thead>
                    <tr class="text-center">
                        <th scope="col" style="width:5%">No</th>
                        <th scope="col" style="width:65%">Nama Subkriteria</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($subkriterias as $index => $subkriteria)
                    <tr class="text-center">
                        <th scope="row">{{$index + 1}}</th>
                        <td>{{$subkriteria->nama_subkriteria}}</td>
                        <td>
                            <span class="badge text-white text-capitalize text-bg-warning edit-link" data-bs-toggle="modal"
                                data-bs-target="#exampleModal3" data-id="{{ $subkriteria->id }}"
                                data-idNama="{{$subkriteria->nama_subkriteria}}">
                                Edit
                            </span> |
                            <span class="badge text-white text-capitalize text-bg-danger delete-link" data-bs-toggle="modal"
                                data-bs-target="#exampleModal2" data-id="{{ $subkriteria->id }}">
                                Delete
                            </span>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {!! $subkriterias->links() !!}
        </div>
    </div>

    {{-- create subkriteria --}}
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <form method="POST" action="{{ route('subkriteria.store') }}">
                @csrf
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah Subkriteria</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <input type="hidden" name="id_kriteria" value="{{request()->id}}" id="">
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="" class="form-label">Nama Subkriteria</label>
                            <input type="text" class="form-control border px-2" id="" name="nama_subkriteria" placeholder="Nama Subkriteria">
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Simpan</button>
                    </div>
            </form>
        </div>
    </div>
    </div>

    {{-- edit subkriteria --}}
    <div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModal3Label" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <form method="POST">
                @csrf
                @method('PUT')
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModal3Label">Edit Subkriteria</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="" class="form-label">Nama Subkriteria</label>
                            <input type="hidden" name="id_subkriteria" id="editInputId">
                            <input type="text" class="form-control border px-2" id="nama_subkriteria"
                                name="nama_subkriteria" placeholder="Nama Subkriteria">
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Edit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    {{-- delete subkriteria --}}
    <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModal2Label" aria-hidden="true">
        <div class="modal-dialog">
            <form method="POST">
                @csrf
                @method('DELETE')
                <input type="hidden" name="id_subkriteria" id="deleteIdInput">

                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModal2Label">Hapus Subkriteria</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        apakah anda yakin ingin menghapus Subkriteria ini?
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Hapus</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    @endslot

</x-app-layout>

<script>
    $(document).ready(function() {
            $('.delete-link').click(function(e) {
                e.preventDefault();
                var id = $(this).data('id');
                $('#deleteIdInput').val(id); // Set the value of the hidden input field
                var formAction = '/subkriteria/destroy';
                $('#exampleModal2 form').attr('action', formAction);
            });
            $('.edit-link').click(function(e) {
                var id = $(this).data('id');
                let nama_subkriteria = $(this).data('idnama');
                $('#nama_subkriteria').val(nama_subkriteria);
                $('#editInputId').val(id);
                console.log(`${nama_subkriteria} ${id}`)
                var formActionEdit = '/subkriteria/update';
                $('#exampleModal3 form').attr('action', formActionEdit);
            });
        });
</script>