routes/web.php
<?php

use App\Models\Kriteria;
use App\Models\Alternatif;
use App\Models\SubKriteria;
use App\Http\Controllers\DataPetugas;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\AlternatifController;
use App\Http\Controllers\PerhitunganController;
use App\Http\Controllers\SubkriteriaController;
use App\Http\Controllers\AlternatifDetailController;
use App\Http\Controllers\PerhitunganSubkriteriaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/logout', [LoginController::class, 'logout']);

Route::group(['middleware' => 'auth'], function () {
    // Halaman Dashboard
    Route::get('/dashboard', function () {
        return view('pages.index', [
            "title" => 'Dashboard',
            "active" => "dashboard",
            "alternatif" => Alternatif::get()->count(),
            "kriteria" => Kriteria::get()->count(),
            "subkriteria" => SubKriteria::get()->count(),
        ]);
    });

    Route::resource('kriteria', KriteriaController::class);
    Route::resource('subkriteria', SubkriteriaController::class);

    Route::get('/alternatif', [AlternatifController::class, 'index']);
    Route::post('/alternatif/store', [AlternatifController::class, 'store']);
    Route::get('/alternatif/edit', [AlternatifController::class, 'edit']);
    Route::put('/alternatif/update', [AlternatifController::class, 'update']);
    Route::delete('/alternatif/destroy', [AlternatifController::class, 'destroy']);

    Route::get('/alternatif_detail', [AlternatifDetailController::class, 'index']);
    Route::post('/alternatif_detail/store', [AlternatifDetailController::class, 'store']);
    Route::get('/alternatif_detail/edit', [AlternatifDetailController::class, 'edit']);
    Route::put('/alternatif_detail/update', [AlternatifDetailController::class, 'update']);
    Route::delete('/alternatif_detail/destroy', [AlternatifDetailController::class, 'destroy']);

    Route::get('/perhitungan', [PerhitunganController::class, 'index']);
    Route::post('/perhitungan/store', [PerhitunganController::class, 'store']);
    Route::get('/perhitungan/hasil', [PerhitunganController::class, 'hasil']);
    Route::get('/perhitungan/edit', [PerhitunganController::class, 'edit']);
    Route::put('/perhitungan/update', [PerhitunganController::class, 'update']);
    Route::delete('/perhitungan/destroy', [PerhitunganController::class, 'destroy']);

    Route::get('/perhitungan_subkriteria', [PerhitunganSubkriteriaController::class, 'index']);
    Route::get('/perhitungan_subkriteria/matrix', [PerhitunganSubkriteriaController::class, 'matrix']);
    Route::get('/perhitungan_subkriteria/hasil', [PerhitunganSubkriteriaController::class, 'hasil']);
    Route::get('/perhitungan_subkriteria/alternatif', [PerhitunganSubkriteriaController::class, 'alternatif']);
    Route::get('/perhitungan_subkriteria/prangkingan', [PerhitunganSubkriteriaController::class, 'prangkingan']);
    Route::post('/perhitungan_subkriteria/store', [PerhitunganSubkriteriaController::class, 'store']);
    Route::get('/perhitungan_subkriteria/edit', [PerhitunganSubkriteriaController::class, 'edit']);
    Route::put('/perhitungan_subkriteria/update', [PerhitunganSubkriteriaController::class, 'update']);
    Route::delete('/perhitungan_subkriteria/destroy', [PerhitunganSubkriteriaController::class, 'destroy']);

    Route::resource('/datapengguna', DataPetugas::class)->except('show', 'create');
});

app/Models/Kriteria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Kriteria extends Model
{
    use HasFactory;

    public function subkriterias() : HasMany {
        return $this->hasMany(SubKriteria::class, 'id_kriteria', 'id');
    }

    public function perhitungans() : HasMany {
        return $this->hasMany(Perhitungan::class, 'id_kriteria', 'id');
    }

    public function nilaiprioritaskriteria() : HasOne {
        return $this->hasOne(NilaiPrioritasKriteria::class, 'id_kriteria', 'id');
    }

    public function subkriteriavalid() : HasOne {
        return $this->hasOne(SubkriteriaValid::class, 'id_kriteria', 'id');
    }

    public function alternatifdetails() : HasMany {
        return $this->HasMany(AlternatifDetail::class, 'id_kriteria', 'id');
    }   
}

app/Http/Controllers/KriteriaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kriteria;
use Illuminate\Http\Request;

class KriteriaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $kriterias = Kriteria::all();

        return view('pages.kriteria.index', ['kriterias' => $kriterias]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(Request $kriteria)
    {
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $kriteriaModel = new Kriteria();
        $kriteriaModel->nama_kriteria = $request->nama_kriteria;

        $kriteriaModel->save();
        return redirect('/kriteria')->with('success', 'Berhasil menambahkan kriteria');
    }

    /**
     * Display the specified resource.
     */
    public function show(Kriteria $kriteria)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Kriteria $kriteria)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Kriteria $kriteria)
    {
        $id = $request->input('id_kriteria');
        $kriteria = Kriteria::where('id', $id)->first();
        $kriteria->nama_kriteria = $request->input('nama_kriteria');
        $kriteria->save();
        return redirect('/kriteria')->with('success', 'Berhasil edit kriteria');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Request $request)
    {
        $id = $request->input('id_kriteria');
        $subkriteria = Kriteria::where('id', $id)->first();
        $subkriteria->delete();
        return redirect('kriteria')->with('success', 'Berhasil menghapus kriteria');
    }
}

resources/views/pages/kriteria/index.blade.php
<x-app-layout>

    @slot('content')
    <div class="container-fluid px-4">
        @section('title')Kriteria @endsection
        <h4 class="mb-2 mt-4">Kriteria</h4>
        <hr>

        <div class="col-12 my-3">
            @if (Auth::user()->admin == 'staff hrd')
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Tambah Kriteria
            </button>
            @endcan
        </div>

        <div class="card mb-4">
            <div class="card-body">
                <table class="table table-striped border">
                    <thead>
                        <tr class="text-center">
                            <th scope="col" style="width:5%">No</th>
                            <th scope="col" style="width:65%">Nama Kriteria</th>
                            @if (Auth::user()->admin == 'staff hrd')
                            <th scope="col">Action</th>
                            @endcan
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($kriterias as $index => $kriteria)
                        <tr class="text-center">
                            <th scope="row">{{$index + 1}}</th>
                            <td>{{$kriteria->nama_kriteria}}</td>
                            @if (Auth::user()->admin == 'staff hrd')
                            <td>
                                <a href="/subkriteria?id={{$kriteria->id}}"
                                    class="btn btn-success btn-sm text-white text-capitalize" style="cursor: pointer;">
                                    Subkriteria
                                </a> |
                                <a class="btn btn-warning btn-sm edit-link text-white text-capitalize" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal3" data-id="{{ $kriteria->id }}"
                                    data-idNama="{{$kriteria->nama_kriteria}}" style="cursor: pointer;">
                                    Edit
                                </a> |
                                <a class="btn btn-danger btn-sm delete-link text-white text-capitalize" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal2" data-id="{{ $kriteria->id }}"
                                    style="cursor: pointer;">
                                    Delete
                                </a>
                            </td>
                            @endif
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <form method="POST" action="{{ route('kriteria.store') }}">
                @csrf
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah Kriteria</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="" class="form-label">Nama Kriteria</label>
                            <input type="text" class="form-control border px-2" id="" name="nama_kriteria"
                                placeholder="Nama Kriteria" autofocus>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Simpan</button>
                    </div>
            </form>
        </div>
    </div>
    </div>

    <div class="modal fade" id="exampleModal3" tabindex="-1" aria-labelledby="exampleModal3Label" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <form method="POST">
                @csrf
                @method('PUT')
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModal3Label">Edit kriteria</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="" class="form-label">Nama Kriteria</label>
                            <input type="hidden" name="id_kriteria" id="editInputId">
                            <input type="text" class="form-control border px-2" id="nama_kriteria" name="nama_kriteria" placeholder="Nama Kriteria">
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Edit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>


    <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModal2Label" aria-hidden="true">
        <div class="modal-dialog">
            <form method="POST">
                @csrf
                @method('DELETE')
                <input type="hidden" name="id_kriteria" id="deleteIdInput">

                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModal2Label">Hapus kriteria</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        apakah anda yakin ingin menghapus kriteria {{$kriteria->nama_kriteria}}?
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success">Hapus</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    @endslot

</x-app-layout>

<script>
    $(document).ready(function() {
        $('.delete-link').click(function(e) {
            e.preventDefault();
            var id = $(this).data('id');
            $('#deleteIdInput').val(id); // Set the value of the hidden input field
            var formAction = '/kriteria/destroy';
            $('#exampleModal2 form').attr('action', formAction);
        });
        $('.edit-link').click(function(e) {
            var id = $(this).data('id');
            let nama_kriteria = $(this).data('idnama');
            $('#nama_kriteria').val(nama_kriteria);
            $('#editInputId').val(id);
            console.log(`${nama_kriteria} ${id}`)
            var formActionEdit = '/kriteria/update';
            $('#exampleModal3 form').attr('action', formActionEdit);
        });
    });

</script>