routes/web.php
<?php

use App\Models\Kriteria;
use App\Models\Alternatif;
use App\Models\SubKriteria;
use App\Http\Controllers\DataPetugas;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\AlternatifController;
use App\Http\Controllers\PerhitunganController;
use App\Http\Controllers\SubkriteriaController;
use App\Http\Controllers\AlternatifDetailController;
use App\Http\Controllers\PerhitunganSubkriteriaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate']);
Route::post('/logout', [LoginController::class, 'logout']);

Route::group(['middleware' => 'auth'], function () {
    // Halaman Dashboard
    Route::get('/dashboard', function () {
        return view('pages.index', [
            "title" => 'Dashboard',
            "active" => "dashboard",
            "alternatif" => Alternatif::get()->count(),
            "kriteria" => Kriteria::get()->count(),
            "subkriteria" => SubKriteria::get()->count(),
        ]);
    });

    Route::resource('kriteria', KriteriaController::class);
    Route::resource('subkriteria', SubkriteriaController::class);

    Route::get('/alternatif', [AlternatifController::class, 'index']);
    Route::post('/alternatif/store', [AlternatifController::class, 'store']);
    Route::get('/alternatif/edit', [AlternatifController::class, 'edit']);
    Route::put('/alternatif/update', [AlternatifController::class, 'update']);
    Route::delete('/alternatif/destroy', [AlternatifController::class, 'destroy']);

    Route::get('/alternatif_detail', [AlternatifDetailController::class, 'index']);
    Route::post('/alternatif_detail/store', [AlternatifDetailController::class, 'store']);
    Route::get('/alternatif_detail/edit', [AlternatifDetailController::class, 'edit']);
    Route::put('/alternatif_detail/update', [AlternatifDetailController::class, 'update']);
    Route::delete('/alternatif_detail/destroy', [AlternatifDetailController::class, 'destroy']);

    Route::get('/perhitungan', [PerhitunganController::class, 'index']);
    Route::post('/perhitungan/store', [PerhitunganController::class, 'store']);
    Route::get('/perhitungan/hasil', [PerhitunganController::class, 'hasil']);
    Route::get('/perhitungan/edit', [PerhitunganController::class, 'edit']);
    Route::put('/perhitungan/update', [PerhitunganController::class, 'update']);
    Route::delete('/perhitungan/destroy', [PerhitunganController::class, 'destroy']);

    Route::get('/perhitungan_subkriteria', [PerhitunganSubkriteriaController::class, 'index']);
    Route::get('/perhitungan_subkriteria/matrix', [PerhitunganSubkriteriaController::class, 'matrix']);
    Route::get('/perhitungan_subkriteria/hasil', [PerhitunganSubkriteriaController::class, 'hasil']);
    Route::get('/perhitungan_subkriteria/alternatif', [PerhitunganSubkriteriaController::class, 'alternatif']);
    Route::get('/perhitungan_subkriteria/prangkingan', [PerhitunganSubkriteriaController::class, 'prangkingan']);
    Route::post('/perhitungan_subkriteria/store', [PerhitunganSubkriteriaController::class, 'store']);
    Route::get('/perhitungan_subkriteria/edit', [PerhitunganSubkriteriaController::class, 'edit']);
    Route::put('/perhitungan_subkriteria/update', [PerhitunganSubkriteriaController::class, 'update']);
    Route::delete('/perhitungan_subkriteria/destroy', [PerhitunganSubkriteriaController::class, 'destroy']);

    Route::resource('/datapengguna', DataPetugas::class)->except('show', 'create');
});

resources/views/pages/datapengguna/create.blade.php
<div class="modal fade" id="mocreat" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-dark" id="exampleModalLabel">Tambah Data Pengguna
                </h3>
                <i class="bi bi-x-lg text-danger" data-bs-dismiss="modal" aria-label="Close"></i>
            </div>
            <form method="post" action="/datapengguna" class="mb-3" enctype="multipart/form-data" id="createsuratmasuk">
                @csrf
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="name" class="form-label text-dark">Nama Lengkap</label>
                        <input type="text" class="form-control border px-2 @error('name') is-invalid @enderror" id="name"
                            name="name" value="{{ old('name') }}" placeholder="Nama Lengkap" min="1" maxlength="10">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>


                    <div class="mb-3">
                        <label for="email" class="form-label text-dark">Alamat Email</label>
                        <input type="text" class="form-control border px-2" id="email" name="email" required
                            value="{{ old('email') }}" placeholder="Alamat Email">

                    </div>

                    <div class="mb-3">
                        <label for="password" class="form-label text-dark">Jabatan</label>
                        <div class="col-sm-12">
                            <select class="form-select border px-2" name="admin">
                                <option value="manager" @if(old('admin')=='manager' ) selected @endif>Manager</option>
                                <option value="admin" @if(old('admin')=='admin' ) selected @endif>Admin</option>
                            </select>

                        </div>
                    </div>

                    <label for="password" class="form-label text-dark">Password</label>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control border px-2 @error('password') is-invalid @enderror"
                            id="password" name="password" required autofocus value="{{ old('password') }}"
                            placeholder="Password" style="height: 40px;">
                    </div>
                    @error('password')
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror

                </div>

                <div class="modal-footer">
                    <a class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close"> Batal</a>
                    <button type="submit" class="btn btn-success">
                        Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/pages/datapengguna/edit.blade.php
<div class="modal fade" id="penggunaedit{{ $user->id }}" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Ubah Data Pengguna</h1>
            </div>
            <form method="post" action="{{ route('datapengguna.update', $user->id) }}" class="mb-3 p-3"
                id="editdatapetugas" enctype="multipart/form-data">
                @method('PATCH')
                @csrf
                <div class="modal-body justify-content-start">

                    <div class="mb-3">
                        <label for="name" class="form-label text-dark">Nama Lengkap</label>
                        <input type="text" class="form-control border px-2 px-2 @error('name') is-invalid @enderror"
                            id="name" name="name" value="{{ $user->name }}" placeholder="Nama Lengkap" min="1"
                            maxlength="10">
                        @error('name')
                        <div class="invalid-feedback">
                            {{ $message }}
                        </div>
                        @enderror
                    </div>


                    <div class="mb-3">
                        <label for="email" class="form-label text-dark">Alamat Email</label>
                        <input type="text" class="form-control border px-2" id="email" name="email" required
                            value="{{ $user->email }}" placeholder="Alamat Email">

                    </div>


                    <div class="mb-3">
                        <label for="password" class="form-label text-dark">Jabatan</label>
                        <div class="col-sm-12">
                            <select class="form-select border px-2" name="admin">
                                <option value="manager" {{ $user->admin == 'manager' ? 'selected' : '' }}>Manager
                                </option>
                                <option value="admin" {{ $user->admin == 'admin' ? 'selected' : '' }}>Admin
                                </option>
                            </select>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger" data-bs-dismiss="modal" aria-label="Close"> Batal</a>
                    <button type="submit" class="btn btn-success">Simpan</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/pages/datapengguna/index.blade.php
<x-app-layout>

    @slot('content')
    <div class="container-fluid px-4">
        @section('title')Data Pengguna @endsection
        <h4 class="mb-2 mt-4">Data Pengguna</h4>
        <hr>

        <a class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#mocreat" data-bs-whatever="@mdo">Tambah
            Pengguna</a>
        @include('pages.datapengguna.create')

        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    Data Pengguna
                </div>
                <div class="card-body">
                    <table class="table table-striped border">
                        <thead class=" text-center">
                            <tr style="text-transform: capitalize">
                                <th>No</th>
                                <th>Nama</th>
                                <th>Email</th>
                                <th>Jabatan</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($user1 as $user)
                            <tr>
                                <td class="text-center">{{ $loop->iteration }}</td>
                                <td class="text-center" style="text-transform: capitalize">{{ $user->name }}</td>
                                <td class="text-center">{{ $user->email }}</td>
                                <td class="text-center" style="text-transform: capitalize">{{ $user->admin }}</td>
                                <td class="d-flex justify-content-center">
                                    <a href="/datapengguna/{{ $user->id }}/edit" class="btn btn-warning text-light me-2"
                                        data-bs-toggle="modal" data-bs-target="#penggunaedit{{ $user->id }}">Ubah
                                    </a>

                                    @include('pages.datapengguna.edit')

                                    <form method="POST" action="{{ route('datapengguna.destroy', $user->id) }}"
                                        class="d-inline">
                                        @method('delete')
                                        @csrf
                                        <input name="_method" type="hidden" value="DELETE">
                                        <button type="button" class="btn btn-xs btn-danger btn-flat"
                                            data-bs-toggle="modal"
                                            data-bs-target="#confirmDeleteModal{{ $user->id }}">Hapus
                                        </button>
                                        <div class="modal fade" id="confirmDeleteModal{{ $user->id }}" tabindex="-1"
                                            aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="confirmDeleteModalLabel">Hapus</h5>
                                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                            aria-label="Close"></button>
                                                    </div>
                                                    <div class="modal-body">
                                                        Apakah Anda yakin ingin menghapus data {{ $user->name }}?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-danger"
                                                            data-bs-dismiss="modal">Close</button>
                                                        <button type="submit" class="btn btn-success">Hapus</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>

                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    @endslot

</x-app-layout>